# Generated by Django 2.2.3 on 2019-07-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('work', models.CharField(max_length=20)),
                ('fnlwgt', models.IntegerField()),
                ('education', models.CharField(max_length=20)),
                ('education_num', models.IntegerField()),
                ('marital_status', models.CharField(max_length=30)),
                ('occupation', models.CharField(max_length=30)),
                ('relationship', models.CharField(max_length=20)),
                ('race', models.CharField(max_length=30)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('capital_gain', models.IntegerField(default=0)),
                ('capital_loss', models.IntegerField(default=0)),
                ('hours_per_week', models.IntegerField()),
                ('native_country', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
