# Generated by Django 2.2.3 on 2019-07-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='adult',
            name='capital_gain',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adult',
            name='capital_loss',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adult',
            name='education_num',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='adult',
            name='fnlwgt',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='adult',
            name='hours_per_week',
            field=models.PositiveIntegerField(),
        ),
    ]
