# Generated by Django 2.2.3 on 2019-07-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20190720_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='native_country',
            field=models.CharField(max_length=50),
        ),
    ]
